### PR TITLE
CDE (Contribution Distribution Engine) Upgrades

### PR DESCRIPTION
**Pull request by kikass13**
### General 
This is the PR relating to everything happening in #164 
you have to read my changelogs in there to get the full feature list :)

### System Overview
CDE_Architecture

### How to install it
```
cd libreselery
sudo python setup.py develop ## proper package install, should install deps as well
```

#### Libreselery
```
cd ~/libreselery
source ~/.libreselery/tokens.env
selery run -c ~/libreselery/selery.yml -d ~/libreselery -r ~/libreselery/results/
```

#### Plugin (testcase)
```
cd libreselery/libreselery/contribution_activity_plugins
python3 hello_world_activity_plugin.py ## start plugin for hello world
python3 git_file_contributors.py ## start plugin for file contributors
python3 github_remote_contributors.py ## start plugin for remote contributors using github api
```

### CODE REVIEW

**Comment by kikass13** [comment]
@Ly0n @fdietze @cornerman

**Comment by Ly0n** [comment]
Thanks @kikass13 for amazing Sunday coding together. The new architecture works perfectly.

**Comment by kikass13** [comment]
We added a plugin which uses awesomelists to pick a single random contributor from 5 random projects and pay them out.
We also tested the payout mechanism, which works fine for now.

**Comment by Ly0n** [comment]
New architecture works with awesome-list integration plugins as example implementation.
Branch tested with:
```
docker build -t libreselery . && env $(cat ~/.libreselery/tokens.env | xargs) ~/libreselery/run.sh ~/awesome-sustainable-technology
```

Native install with:
```
pip3 install . 
```

**Comment by Ly0n** [comment]
For runing on the host machine use the following command:
```
env $(cat ~/.libreselery/tokens.env | xargs) selery run -c ~/awesome-sustainable-technology/selery.yml -d ~/awesome-sustainable-technology -r ~/.libreselery/results/
 ```

**Pull request merged**
